Setup base Github Actions support
DiscordHooks/github-actions-discord-webhook pull request #4
Opened 2019-09-22 21:40 UTC by lcombs15

Closes #2 

Passing Build:
![image](https://user-images.githubusercontent.com/3866197/65394807-132fa800-dd60-11e9-8dc3-56c746f8cd01.png)

Failing Build:
![image](https://user-images.githubusercontent.com/3866197/65394808-1aef4c80-dd60-11e9-8e77-2d8670e432cb.png)

2019-09-22 21:41 UTC, tiemonl approved these changes

2019-09-22 21:48 UTC, tiemonl approved these changes

2019-09-23 17:18 UTC, iamtraction requested changes
Just a few changes. Other than that, it looks good to me. 👌

2019-09-23 17:18 UTC, k3rn31p4nic commented on send.sh
> +  echo -e "WARNING!!\nYou need to pass the WEBHOOK_URL environment variable as the second argument to this script.\nFor details & guide, visit: https://github.com/DiscordHooks/travis-ci-discord-webho
```suggestion
  echo -e "WARNING!!\nYou need to pass the WEBHOOK_URL environment variable as the second argument to this script.\nFor details & guide, visit: https://github.com/DiscordHooks/github-actions-discord-webhook" && exit
```

2019-09-23 17:18 UTC, k3rn31p4nic commented on send.sh
> +AVATAR="https://avatars0.githubusercontent.com/u/44036562?s=200"
```suggestion
AVATAR="https://github.com/actions.png"
```

2019-09-24 15:46 UTC, iamtraction approved these changes
LGTM 👌 
And you've been invited to DiscordHooks org. Welcome!

2019-09-24 15:47 UTC, merged